# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/AXI_DEBUG_BD_wrapper.xdc

# Block Designs: bd/AXI_DEBUG_BD/AXI_DEBUG_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DEBUG_BD || ORIG_REF_NAME==AXI_DEBUG_BD} -quiet] -quiet

# IP: bd/AXI_DEBUG_BD/ip/AXI_DEBUG_BD_processing_system7_0_0/AXI_DEBUG_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DEBUG_BD_processing_system7_0_0 || ORIG_REF_NAME==AXI_DEBUG_BD_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_DEBUG_BD/ip/AXI_DEBUG_BD_LED_CONTROLLER_0_0/AXI_DEBUG_BD_LED_CONTROLLER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DEBUG_BD_LED_CONTROLLER_0_0 || ORIG_REF_NAME==AXI_DEBUG_BD_LED_CONTROLLER_0_0} -quiet] -quiet

# IP: bd/AXI_DEBUG_BD/ip/AXI_DEBUG_BD_ps7_0_axi_periph_0/AXI_DEBUG_BD_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DEBUG_BD_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_DEBUG_BD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_DEBUG_BD/ip/AXI_DEBUG_BD_rst_ps7_0_50M_0/AXI_DEBUG_BD_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DEBUG_BD_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_DEBUG_BD_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/AXI_DEBUG_BD/ip/AXI_DEBUG_BD_auto_pc_0/AXI_DEBUG_BD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_DEBUG_BD_auto_pc_0 || ORIG_REF_NAME==AXI_DEBUG_BD_auto_pc_0} -quiet] -quiet

# XDC: bd/AXI_DEBUG_BD/ip/AXI_DEBUG_BD_processing_system7_0_0/AXI_DEBUG_BD_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI_DEBUG_BD_processing_system7_0_0 || ORIG_REF_NAME==AXI_DEBUG_BD_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/AXI_DEBUG_BD/ip/AXI_DEBUG_BD_rst_ps7_0_50M_0/AXI_DEBUG_BD_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI_DEBUG_BD_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_DEBUG_BD_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/AXI_DEBUG_BD/ip/AXI_DEBUG_BD_rst_ps7_0_50M_0/AXI_DEBUG_BD_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI_DEBUG_BD_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_DEBUG_BD_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/AXI_DEBUG_BD/ip/AXI_DEBUG_BD_auto_pc_0/AXI_DEBUG_BD_auto_pc_0_ooc.xdc

# XDC: bd/AXI_DEBUG_BD/AXI_DEBUG_BD_ooc.xdc
