# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hdmi_cons.xdc

# XDC: imports/Repos/BlackboardRevB_MasterXDC.xdc

# Block Designs: bd/HDMI_CONTROLLER_BD/HDMI_CONTROLLER_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_CONTROLLER_BD || ORIG_REF_NAME==HDMI_CONTROLLER_BD} -quiet] -quiet

# IP: bd/HDMI_CONTROLLER_BD/ip/HDMI_CONTROLLER_BD_VGA_controller_0_0/HDMI_CONTROLLER_BD_VGA_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_CONTROLLER_BD_VGA_controller_0_0 || ORIG_REF_NAME==HDMI_CONTROLLER_BD_VGA_controller_0_0} -quiet] -quiet

# IP: bd/HDMI_CONTROLLER_BD/ip/HDMI_CONTROLLER_BD_clk_wiz_0_0/HDMI_CONTROLLER_BD_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_CONTROLLER_BD_clk_wiz_0_0 || ORIG_REF_NAME==HDMI_CONTROLLER_BD_clk_wiz_0_0} -quiet] -quiet

# IP: bd/HDMI_CONTROLLER_BD/ip/HDMI_CONTROLLER_BD_color_logic_0_0/HDMI_CONTROLLER_BD_color_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_CONTROLLER_BD_color_logic_0_0 || ORIG_REF_NAME==HDMI_CONTROLLER_BD_color_logic_0_0} -quiet] -quiet

# IP: bd/HDMI_CONTROLLER_BD/ip/HDMI_CONTROLLER_BD_hdmi_tx_0_0/HDMI_CONTROLLER_BD_hdmi_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_CONTROLLER_BD_hdmi_tx_0_0 || ORIG_REF_NAME==HDMI_CONTROLLER_BD_hdmi_tx_0_0} -quiet] -quiet

# XDC: bd/HDMI_CONTROLLER_BD/ip/HDMI_CONTROLLER_BD_clk_wiz_0_0/HDMI_CONTROLLER_BD_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_CONTROLLER_BD_clk_wiz_0_0 || ORIG_REF_NAME==HDMI_CONTROLLER_BD_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/HDMI_CONTROLLER_BD/ip/HDMI_CONTROLLER_BD_clk_wiz_0_0/HDMI_CONTROLLER_BD_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_CONTROLLER_BD_clk_wiz_0_0 || ORIG_REF_NAME==HDMI_CONTROLLER_BD_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/HDMI_CONTROLLER_BD/ip/HDMI_CONTROLLER_BD_clk_wiz_0_0/HDMI_CONTROLLER_BD_clk_wiz_0_0_ooc.xdc

# XDC: bd/HDMI_CONTROLLER_BD/HDMI_CONTROLLER_BD_ooc.xdc
