webtalk_init -webtalk_dir /home/necryotiks/Documents/Repos/WSU-CPTE/EE324/Self_Checking_Testbench/Self_Checking_Testbench.sim/sim_1/behav/xsim/xsim.dir/assert_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 20 18:45:28 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ce1428ef-3768-4c6a-81e7-0d53650b3c91" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "62112384433041d7824bc6d32bb98972" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "27" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1594.910 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114820_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2168388400 -regid "" -xml /home/necryotiks/Documents/Repos/WSU-CPTE/EE324/Self_Checking_Testbench/Self_Checking_Testbench.sim/sim_1/behav/xsim/xsim.dir/assert_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/necryotiks/Documents/Repos/WSU-CPTE/EE324/Self_Checking_Testbench/Self_Checking_Testbench.sim/sim_1/behav/xsim/xsim.dir/assert_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/necryotiks/Documents/Repos/WSU-CPTE/EE324/Self_Checking_Testbench/Self_Checking_Testbench.sim/sim_1/behav/xsim/xsim.dir/assert_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
