# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/RTM_cons.xdc

# Block Designs: bd/Reaction_Time_Averager/Reaction_Time_Averager.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager || ORIG_REF_NAME==Reaction_Time_Averager} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_LSFR_0_0/Reaction_Time_Averager_LSFR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_LSFR_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_LSFR_0_0} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_HZ_Counter_0_0/Reaction_Time_Averager_HZ_Counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_HZ_Counter_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_HZ_Counter_0_0} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_RTM_FSM_0_0/Reaction_Time_Averager_RTM_FSM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_RTM_FSM_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_RTM_FSM_0_0} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_stopwatch_ssd_driver_0_0/Reaction_Time_Averager_stopwatch_ssd_driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_stopwatch_ssd_driver_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_stopwatch_ssd_driver_0_0} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_ssd_mux_0_0/Reaction_Time_Averager_ssd_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_ssd_mux_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_ssd_mux_0_0} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_ssd_dec_0_0/Reaction_Time_Averager_ssd_dec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_ssd_dec_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_ssd_dec_0_0} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_proc_sys_reset_0_0/Reaction_Time_Averager_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_proc_sys_reset_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_Accumuator_0_0/Reaction_Time_Averager_Accumuator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_Accumuator_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_Accumuator_0_0} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_BCD_TO_BINARY_0_0/Reaction_Time_Averager_BCD_TO_BINARY_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_BCD_TO_BINARY_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_BCD_TO_BINARY_0_0} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_BINARY_TO_BCD_0_0/Reaction_Time_Averager_BINARY_TO_BCD_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_BINARY_TO_BCD_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_BINARY_TO_BCD_0_0} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_EXTRA_THICC_MUX_0_0/Reaction_Time_Averager_EXTRA_THICC_MUX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_EXTRA_THICC_MUX_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_EXTRA_THICC_MUX_0_0} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_xlslice_0_0/Reaction_Time_Averager_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_xlslice_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_xlslice_0_0} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_xlslice_0_1/Reaction_Time_Averager_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_xlslice_0_1 || ORIG_REF_NAME==Reaction_Time_Averager_xlslice_0_1} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_xlslice_0_2/Reaction_Time_Averager_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_xlslice_0_2 || ORIG_REF_NAME==Reaction_Time_Averager_xlslice_0_2} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_xlslice_0_3/Reaction_Time_Averager_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_xlslice_0_3 || ORIG_REF_NAME==Reaction_Time_Averager_xlslice_0_3} -quiet] -quiet

# IP: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_Divider_0_0/Reaction_Time_Averager_Divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_Divider_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_Divider_0_0} -quiet] -quiet

# XDC: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_proc_sys_reset_0_0/Reaction_Time_Averager_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_proc_sys_reset_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_proc_sys_reset_0_0/Reaction_Time_Averager_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Reaction_Time_Averager_proc_sys_reset_0_0 || ORIG_REF_NAME==Reaction_Time_Averager_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Reaction_Time_Averager/ip/Reaction_Time_Averager_proc_sys_reset_0_0/Reaction_Time_Averager_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/Reaction_Time_Averager/Reaction_Time_Averager_ooc.xdc
