@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue Nov 13 15:34:46 -0800 2018
=======
<<<<<<< HEAD
REM Generated by Vivado on Sat Nov 10 21:42:40 -0800 2018
=======
REM Generated by Vivado on Fri Nov 09 16:11:54 -0800 2018
>>>>>>> 8c676840f2d6ed352e8a720fb7e570aabcf8c2b5
>>>>>>> f5b32d4ca83d31785747b52779843e931249981e
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
echo "xvlog --incr --relax -prj test_SERIAL_ADDER_vlog.prj"
call xvlog  --incr --relax -prj test_SERIAL_ADDER_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
echo "xvhdl --incr --relax -prj test_SERIAL_ADDER_vhdl.prj"
call xvhdl  --incr --relax -prj test_SERIAL_ADDER_vhdl.prj -log xvhdl.log
call type xvhdl.log >> compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
