# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test.xdc

# Block Designs: bd/AXI_Test/AXI_Test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Test || ORIG_REF_NAME==AXI_Test} -quiet] -quiet

# IP: bd/AXI_Test/ip/AXI_Test_processing_system7_0_0/AXI_Test_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Test_processing_system7_0_0 || ORIG_REF_NAME==AXI_Test_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_Test/ip/AXI_Test_axi_gpio_0_0/AXI_Test_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Test_axi_gpio_0_0 || ORIG_REF_NAME==AXI_Test_axi_gpio_0_0} -quiet] -quiet

# IP: bd/AXI_Test/ip/AXI_Test_ps7_0_axi_periph_0/AXI_Test_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Test_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_Test_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_Test/ip/AXI_Test_rst_ps7_0_50M_0/AXI_Test_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Test_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_Test_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/AXI_Test/ip/AXI_Test_timer_ssd_driver_0_0/AXI_Test_timer_ssd_driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Test_timer_ssd_driver_0_0 || ORIG_REF_NAME==AXI_Test_timer_ssd_driver_0_0} -quiet] -quiet

# IP: bd/AXI_Test/ip/AXI_Test_auto_pc_0/AXI_Test_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Test_auto_pc_0 || ORIG_REF_NAME==AXI_Test_auto_pc_0} -quiet] -quiet

# XDC: bd/AXI_Test/ip/AXI_Test_processing_system7_0_0/AXI_Test_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI_Test_processing_system7_0_0 || ORIG_REF_NAME==AXI_Test_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/AXI_Test/ip/AXI_Test_axi_gpio_0_0/AXI_Test_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI_Test_axi_gpio_0_0 || ORIG_REF_NAME==AXI_Test_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/AXI_Test/ip/AXI_Test_axi_gpio_0_0/AXI_Test_axi_gpio_0_0_ooc.xdc

# XDC: bd/AXI_Test/ip/AXI_Test_axi_gpio_0_0/AXI_Test_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI_Test_axi_gpio_0_0 || ORIG_REF_NAME==AXI_Test_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/AXI_Test/ip/AXI_Test_rst_ps7_0_50M_0/AXI_Test_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI_Test_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_Test_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/AXI_Test/ip/AXI_Test_rst_ps7_0_50M_0/AXI_Test_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI_Test_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_Test_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/AXI_Test/ip/AXI_Test_rst_ps7_0_50M_0/AXI_Test_rst_ps7_0_50M_0_ooc.xdc

# XDC: bd/AXI_Test/ip/AXI_Test_auto_pc_0/AXI_Test_auto_pc_0_ooc.xdc

# XDC: bd/AXI_Test/AXI_Test_ooc.xdc
