# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Necryotiks/AppData/Roaming/SPB_Data/WSU-CPTE/Module_13/Module_13.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci
# IP: The module: 'hdmi_tx_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Necryotiks/AppData/Roaming/SPB_Data/WSU-CPTE/Module_13/Module_13.srcs/sources_1/ip/hdmi_tx_0/sim/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/Necryotiks/AppData/Roaming/SPB_Data/WSU-CPTE/Module_13/Module_13.srcs/sources_1/ip/hdmi_tx_0/sim/clk_wiz_0/clk_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Necryotiks/AppData/Roaming/SPB_Data/WSU-CPTE/Module_13/Module_13.srcs/sources_1/ip/hdmi_tx_0/sim/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: c:/Users/Necryotiks/AppData/Roaming/SPB_Data/WSU-CPTE/Module_13/Module_13.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci
# IP: The module: 'hdmi_tx_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Necryotiks/AppData/Roaming/SPB_Data/WSU-CPTE/Module_13/Module_13.srcs/sources_1/ip/hdmi_tx_0/sim/clk_wiz_0/clk_wiz_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/Necryotiks/AppData/Roaming/SPB_Data/WSU-CPTE/Module_13/Module_13.srcs/sources_1/ip/hdmi_tx_0/sim/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Necryotiks/AppData/Roaming/SPB_Data/WSU-CPTE/Module_13/Module_13.srcs/sources_1/ip/hdmi_tx_0/sim/clk_wiz_0/clk_wiz_0_ooc.xdc
