# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SVD_DRIVER_BD/SVD_DRIVER_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SVD_DRIVER_BD || ORIG_REF_NAME==SVD_DRIVER_BD} -quiet] -quiet

# IP: bd/SVD_DRIVER_BD/ip/SVD_DRIVER_BD_SVD_DRIVER_0_0/SVD_DRIVER_BD_SVD_DRIVER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SVD_DRIVER_BD_SVD_DRIVER_0_0 || ORIG_REF_NAME==SVD_DRIVER_BD_SVD_DRIVER_0_0} -quiet] -quiet

# XDC: bd/SVD_DRIVER_BD/SVD_DRIVER_BD_ooc.xdc
