# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/CMP_wrapper_cons.xdc

# Block Designs: bd/CMP/CMP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP || ORIG_REF_NAME==CMP} -quiet] -quiet

# IP: bd/CMP/ip/CMP_Multiplier_0_1/CMP_Multiplier_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_Multiplier_0_1 || ORIG_REF_NAME==CMP_Multiplier_0_1} -quiet] -quiet

# IP: bd/CMP/ip/CMP_PIPO_0_1/CMP_PIPO_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_PIPO_0_1 || ORIG_REF_NAME==CMP_PIPO_0_1} -quiet] -quiet

# IP: bd/CMP/ip/CMP_PIPO_1_0/CMP_PIPO_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_PIPO_1_0 || ORIG_REF_NAME==CMP_PIPO_1_0} -quiet] -quiet

# IP: bd/CMP/ip/CMP_PIPO_1_1/CMP_PIPO_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_PIPO_1_1 || ORIG_REF_NAME==CMP_PIPO_1_1} -quiet] -quiet

# IP: bd/CMP/ip/CMP_Comparator_0_0/CMP_Comparator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_Comparator_0_0 || ORIG_REF_NAME==CMP_Comparator_0_0} -quiet] -quiet

# XDC: bd/CMP/CMP_ooc.xdc
