# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/CLA_wrapper_cons.xdc

# Block Designs: bd/CLA_ADDER/CLA_ADDER.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLA_ADDER || ORIG_REF_NAME==CLA_ADDER} -quiet] -quiet

# IP: bd/CLA_ADDER/ip/CLA_ADDER_CLA_0_0/CLA_ADDER_CLA_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLA_ADDER_CLA_0_0 || ORIG_REF_NAME==CLA_ADDER_CLA_0_0} -quiet] -quiet

# IP: bd/CLA_ADDER/ip/CLA_ADDER_ssd_dec_0_0/CLA_ADDER_ssd_dec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLA_ADDER_ssd_dec_0_0 || ORIG_REF_NAME==CLA_ADDER_ssd_dec_0_0} -quiet] -quiet

# IP: bd/CLA_ADDER/ip/CLA_ADDER_temp_mux_input_0_0/CLA_ADDER_temp_mux_input_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLA_ADDER_temp_mux_input_0_0 || ORIG_REF_NAME==CLA_ADDER_temp_mux_input_0_0} -quiet] -quiet

# IP: bd/CLA_ADDER/ip/CLA_ADDER_ssd_mux_0_0/CLA_ADDER_ssd_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLA_ADDER_ssd_mux_0_0 || ORIG_REF_NAME==CLA_ADDER_ssd_mux_0_0} -quiet] -quiet

# XDC: bd/CLA_ADDER/CLA_ADDER_ooc.xdc
