# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/rgb.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_RGB_PWM_0_0/design_2_RGB_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_RGB_PWM_0_0 || ORIG_REF_NAME==design_2_RGB_PWM_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ps7_0_axi_periph_0/design_2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_ps7_0_50M_0/design_2_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_2_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_PWM_CLK_EN_0_0/design_2_PWM_CLK_EN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_PWM_CLK_EN_0_0 || ORIG_REF_NAME==design_2_PWM_CLK_EN_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_PWM_CLK_EN_0_3/design_2_PWM_CLK_EN_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_PWM_CLK_EN_0_3 || ORIG_REF_NAME==design_2_PWM_CLK_EN_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_PWM_CLK_EN_0_4/design_2_PWM_CLK_EN_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_PWM_CLK_EN_0_4 || ORIG_REF_NAME==design_2_PWM_CLK_EN_0_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_DUTY_CYCLE_0_0/design_2_DUTY_CYCLE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_DUTY_CYCLE_0_0 || ORIG_REF_NAME==design_2_DUTY_CYCLE_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_DUTY_CYCLE_0_1/design_2_DUTY_CYCLE_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_DUTY_CYCLE_0_1 || ORIG_REF_NAME==design_2_DUTY_CYCLE_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_DUTY_CYCLE_0_2/design_2_DUTY_CYCLE_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_DUTY_CYCLE_0_2 || ORIG_REF_NAME==design_2_DUTY_CYCLE_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_0_0/design_2_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_0_0 || ORIG_REF_NAME==design_2_xlslice_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_0_1/design_2_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_0_1 || ORIG_REF_NAME==design_2_xlslice_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_0_2/design_2_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_0_2 || ORIG_REF_NAME==design_2_xlslice_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_pc_0 || ORIG_REF_NAME==design_2_auto_pc_0} -quiet] -quiet

# XDC: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_rst_ps7_0_50M_0/design_2_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_2_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_rst_ps7_0_50M_0/design_2_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_2_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0_ooc.xdc

# XDC: bd/design_2/design_2_ooc.xdc
