##LEDS
#IO_L14P_T2_SRCC_34 Schematic name=LD0
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports {o_LED[0]}]
#IO_L14N_T2_SRCC_34 Schematic name=LD1
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports {o_LED[1]}]
#IO_0_34 Schematic name=LD2
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports {o_LED[2]}]
#IO_L15P_T2_DQS_34 Schematic name=LD3
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports {o_LED[3]}]

set_property PACKAGE_PIN U13 [get_ports {o_RGB_0_0[0]}]
set_property PACKAGE_PIN T19 [get_ports {o_RGB_0_0[1]}]
set_property PACKAGE_PIN W20 [get_ports {o_RGB_0_0[2]}]
set_property PACKAGE_PIN V20 [get_ports {o_RGB_1_0[1]}]
set_property PACKAGE_PIN Y19 [get_ports {o_RGB_1_0[0]}]
set_property PACKAGE_PIN W19 [get_ports {o_RGB_1_0[2]}]
set_property PACKAGE_PIN W18 [get_ports {o_RGB_2_0[0]}]
set_property PACKAGE_PIN W16 [get_ports {o_RGB_2_0[1]}]
set_property PACKAGE_PIN Y18 [get_ports {o_RGB_2_0[2]}]
set_property PACKAGE_PIN Y14 [get_ports {o_RGB_3_0[0]}]
set_property PACKAGE_PIN Y16 [get_ports {o_RGB_3_0[1]}]
set_property PACKAGE_PIN Y17 [get_ports {o_RGB_3_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_RGB_0_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_RGB_0_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_RGB_0_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_RGB_1_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_RGB_1_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_RGB_1_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_RGB_2_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_RGB_2_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_RGB_2_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_RGB_3_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_RGB_3_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_RGB_3_0[0]}]

set_property PACKAGE_PIN M14 [get_ports {i_BTN_0[3]}]
set_property PACKAGE_PIN P15 [get_ports {i_BTN_0[2]}]
set_property PACKAGE_PIN W13 [get_ports {i_BTN_0[1]}]
set_property PACKAGE_PIN W14 [get_ports {i_BTN_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_BTN_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_BTN_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_BTN_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_BTN_0[0]}]
set_property PACKAGE_PIN M15 [get_ports {i_SW_0[7]}]
set_property PACKAGE_PIN L15 [get_ports {i_SW_0[6]}]
set_property PACKAGE_PIN P14 [get_ports {i_SW_0[5]}]
set_property PACKAGE_PIN R14 [get_ports {i_SW_0[4]}]
set_property PACKAGE_PIN N16 [get_ports {i_SW_0[3]}]
set_property PACKAGE_PIN R16 [get_ports {i_SW_0[2]}]
set_property PACKAGE_PIN U20 [get_ports {i_SW_0[1]}]
set_property PACKAGE_PIN R17 [get_ports {i_SW_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_SW_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_SW_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_SW_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_SW_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_SW_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_SW_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_SW_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_SW_0[0]}]
