# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/module_4_cons.xdc

# Block Designs: bd/PWM_IP_BD/PWM_IP_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_IP_BD || ORIG_REF_NAME==PWM_IP_BD} -quiet] -quiet

# IP: bd/PWM_IP_BD/ip/PWM_IP_BD_processing_system7_0_0/PWM_IP_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_IP_BD_processing_system7_0_0 || ORIG_REF_NAME==PWM_IP_BD_processing_system7_0_0} -quiet] -quiet

# IP: bd/PWM_IP_BD/ip/PWM_IP_BD_ps7_0_axi_periph_0/PWM_IP_BD_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_IP_BD_ps7_0_axi_periph_0 || ORIG_REF_NAME==PWM_IP_BD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PWM_IP_BD/ip/PWM_IP_BD_rst_ps7_0_50M_0/PWM_IP_BD_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_IP_BD_rst_ps7_0_50M_0 || ORIG_REF_NAME==PWM_IP_BD_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/PWM_IP_BD/ip/PWM_IP_BD_PWM_DRIVER_1_0/PWM_IP_BD_PWM_DRIVER_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_IP_BD_PWM_DRIVER_1_0 || ORIG_REF_NAME==PWM_IP_BD_PWM_DRIVER_1_0} -quiet] -quiet

# IP: bd/PWM_IP_BD/ip/PWM_IP_BD_auto_pc_0/PWM_IP_BD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_IP_BD_auto_pc_0 || ORIG_REF_NAME==PWM_IP_BD_auto_pc_0} -quiet] -quiet

# XDC: bd/PWM_IP_BD/ip/PWM_IP_BD_processing_system7_0_0/PWM_IP_BD_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PWM_IP_BD_processing_system7_0_0 || ORIG_REF_NAME==PWM_IP_BD_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/PWM_IP_BD/ip/PWM_IP_BD_rst_ps7_0_50M_0/PWM_IP_BD_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PWM_IP_BD_rst_ps7_0_50M_0 || ORIG_REF_NAME==PWM_IP_BD_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PWM_IP_BD/ip/PWM_IP_BD_rst_ps7_0_50M_0/PWM_IP_BD_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PWM_IP_BD_rst_ps7_0_50M_0 || ORIG_REF_NAME==PWM_IP_BD_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PWM_IP_BD/ip/PWM_IP_BD_auto_pc_0/PWM_IP_BD_auto_pc_0_ooc.xdc

# XDC: bd/PWM_IP_BD/PWM_IP_BD_ooc.xdc
