# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Sergaljerk/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-2748-DESKTOP-J2UKM9F/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z007sclg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Sergaljerk/WSU-CPTE/Project6.1_VHDL/Project6.1_VHDL.cache/wt [current_project]
set_property parent.project_path C:/Users/Sergaljerk/WSU-CPTE/Project6.1_VHDL/Project6.1_VHDL.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Sergaljerk/WSU-CPTE/Project6.1_VHDL/Project6.1_VHDL.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Sergaljerk/WSU-CPTE/Project6.1_VHDL/Project6.1_VHDL.srcs/sources_1/new/FA_vhdl.vhd
  C:/Users/Sergaljerk/WSU-CPTE/Project6.1_VHDL/Project6.1_VHDL.srcs/sources_1/new/HA_vhdl.vhd
  C:/Users/Sergaljerk/WSU-CPTE/Project6.1_VHDL/Project6.1_VHDL.srcs/sources_1/new/cmp_bitslice.vhd
  C:/Users/Sergaljerk/WSU-CPTE/Project6.1_VHDL/Project6.1_VHDL.srcs/sources_1/new/comparator_vhdl.vhd
  C:/Users/Sergaljerk/WSU-CPTE/Project6.1_VHDL/Project6.1_VHDL.srcs/sources_1/new/rippleCarryAdder_vhdl.vhd
  C:/Users/Sergaljerk/WSU-CPTE/Project6.1_VHDL/Project6.1_VHDL.srcs/sources_1/new/arith_vhdl_tb.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Sergaljerk/WSU-CPTE/Project6.1_VHDL/Project6.1_VHDL.srcs/constrs_1/new/arith_vhdl_cons.xdc
set_property used_in_implementation false [get_files C:/Users/Sergaljerk/WSU-CPTE/Project6.1_VHDL/Project6.1_VHDL.srcs/constrs_1/new/arith_vhdl_cons.xdc]


synth_design -top arith_vhdl_tb -part xc7z007sclg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef arith_vhdl_tb.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file arith_vhdl_tb_utilization_synth.rpt -pb arith_vhdl_tb_utilization_synth.pb"
