@echo off
REM ****************************************************************************
<<<<<<< HEAD
REM Vivado (TM) v2018.2 (64-bit)
=======
REM Vivado (TM) v2017.4 (64-bit)
>>>>>>> master
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue Aug 28 18:06:57 -0700 2018
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
=======
REM Generated by Vivado on Wed Jul 25 17:49:10 -0700 2018
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
>>>>>>> master
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
call xsim clk_testbench_behav -key {Behavioral:sim_1:Functional:clk_testbench} -tclbatch clk_testbench.tcl -view C:/Users/Sergaljerk/WSU-CPTE/Project5.3/clk_testbench_behav.wcfg -log simulate.log
=======
call xsim clk_testbench_behav -key {Behavioral:sim_1:Functional:clk_testbench} -tclbatch clk_testbench.tcl -view C:/Users/Sergaljerk/Project5.3/clk_testbench_behav.wcfg -log simulate.log
>>>>>>> master
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
