@echo off
REM ****************************************************************************
<<<<<<< HEAD
REM Vivado (TM) v2018.2 (64-bit)
=======
REM Vivado (TM) v2017.4 (64-bit)
>>>>>>> master
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue Aug 28 18:06:52 -0700 2018
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
=======
REM Generated by Vivado on Wed Jul 25 17:49:08 -0700 2018
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
>>>>>>> master
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
call xelab  -wto b9cb99f3263c446aa95d9c0f75df3199 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot clk_testbench_behav xil_defaultlib.clk_testbench xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
