#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 30 18:46:14 PDT 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim dctb_behav -key {Behavioral:sim_1:Functional:dctb} -tclbatch dctb.tcl -protoinst "protoinst_files/bd_36cd.protoinst" -log simulate.log"
xsim dctb_behav -key {Behavioral:sim_1:Functional:dctb} -tclbatch dctb.tcl -protoinst "protoinst_files/bd_36cd.protoinst" -log simulate.log

