webtalk_init -webtalk_dir /home/sergaljerk/Documents/Repos/WSU-CPTE/EE324/Module_2/Module_2.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-08-31 00:33:20" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "l9vklqsgui2ursu7d57lrnif83" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 1700 Eight-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994.412 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "14" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "10.473 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1567236765000" -context "sdk\\\\bsp/1567236765000"
webtalk_add_data -client sdk -key hwid -value "1567236313000" -context "sdk\\\\bsp/1567236765000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1567236765000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1567236765000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1567236765000"
webtalk_add_data -client sdk -key uid -value "1567236769000" -context "sdk\\\\application/1567236769000"
webtalk_add_data -client sdk -key hwid -value "1567236313000" -context "sdk\\\\application/1567236769000"
webtalk_add_data -client sdk -key bspid -value "1567236765000" -context "sdk\\\\application/1567236769000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1567236769000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1567236769000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1567236769000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1567236769000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1567236769000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1567236769000"
webtalk_add_data -client sdk -key projSize -value "191.62109375" -context "sdk\\\\application/1567236769000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1567236800288"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1567236800288"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1567236800288"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1567236800288"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1567236800288"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1567236800288"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1567236800288"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1567236800288"
webtalk_transmit -clientid 1656632391 -regid "" -xml /home/sergaljerk/Documents/Repos/WSU-CPTE/EE324/Module_2/Module_2.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/sergaljerk/Documents/Repos/WSU-CPTE/EE324/Module_2/Module_2.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/sergaljerk/Documents/Repos/WSU-CPTE/EE324/Module_2/Module_2.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
