# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/hdmi_cons.xdc

# Block Designs: bd/TEST/TEST.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TEST || ORIG_REF_NAME==TEST} -quiet] -quiet

# IP: bd/TEST/ip/TEST_VGA_PORCH_0_0/TEST_VGA_PORCH_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TEST_VGA_PORCH_0_0 || ORIG_REF_NAME==TEST_VGA_PORCH_0_0} -quiet] -quiet

# IP: bd/TEST/ip/TEST_VGA_SYNC_0_0/TEST_VGA_SYNC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TEST_VGA_SYNC_0_0 || ORIG_REF_NAME==TEST_VGA_SYNC_0_0} -quiet] -quiet

# IP: bd/TEST/ip/TEST_VGA_COLOR_0_0/TEST_VGA_COLOR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TEST_VGA_COLOR_0_0 || ORIG_REF_NAME==TEST_VGA_COLOR_0_0} -quiet] -quiet

# IP: bd/TEST/ip/TEST_clk_wiz_0/TEST_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TEST_clk_wiz_0 || ORIG_REF_NAME==TEST_clk_wiz_0} -quiet] -quiet

# XDC: bd/TEST/ip/TEST_clk_wiz_0/TEST_clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TEST_clk_wiz_0 || ORIG_REF_NAME==TEST_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/TEST/ip/TEST_clk_wiz_0/TEST_clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TEST_clk_wiz_0 || ORIG_REF_NAME==TEST_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/TEST/ip/TEST_clk_wiz_0/TEST_clk_wiz_0_ooc.xdc

# XDC: bd/TEST/TEST_ooc.xdc
