# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hdmi_cons.xdc

# Block Designs: bd/CHAR_ROM_DISPLAY/CHAR_ROM_DISPLAY.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY || ORIG_REF_NAME==CHAR_ROM_DISPLAY} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_VGA_controller_0_0/CHAR_ROM_DISPLAY_VGA_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_VGA_controller_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_VGA_controller_0_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_clk_wiz_0_0/CHAR_ROM_DISPLAY_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_clk_wiz_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_clk_wiz_0_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_hdmi_tx_0_0/CHAR_ROM_DISPLAY_hdmi_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_hdmi_tx_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_hdmi_tx_0_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_ASCII_addr_gen_0_0/CHAR_ROM_DISPLAY_ASCII_addr_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_ASCII_addr_gen_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_ASCII_addr_gen_0_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_char_rom_0_0/CHAR_ROM_DISPLAY_char_rom_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_char_rom_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_char_rom_0_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_processing_system7_0_0/CHAR_ROM_DISPLAY_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_processing_system7_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_processing_system7_0_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_CHAR_ROM_CONTROLLER_0_0/CHAR_ROM_DISPLAY_CHAR_ROM_CONTROLLER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_CHAR_ROM_CONTROLLER_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_CHAR_ROM_CONTROLLER_0_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_xbar_0/CHAR_ROM_DISPLAY_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_xbar_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_xbar_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_ps7_0_axi_periph_0/CHAR_ROM_DISPLAY_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_ps7_0_axi_periph_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_rst_ps7_0_50M_0/CHAR_ROM_DISPLAY_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_rst_ps7_0_50M_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_C_ROM_LOGIC_0_0/CHAR_ROM_DISPLAY_C_ROM_LOGIC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_C_ROM_LOGIC_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_C_ROM_LOGIC_0_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_xlconstant_0_0/CHAR_ROM_DISPLAY_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_xlconstant_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_xlconstant_0_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_xlconstant_0_1/CHAR_ROM_DISPLAY_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_xlconstant_0_1 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_xlconstant_0_1} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_xlconstant_1_0/CHAR_ROM_DISPLAY_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_xlconstant_1_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_xlconstant_1_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_xlconstant_1_1/CHAR_ROM_DISPLAY_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_xlconstant_1_1 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_xlconstant_1_1} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_xlconstant_3_0/CHAR_ROM_DISPLAY_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_xlconstant_3_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_xlconstant_3_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_RAM_RANGLER_FSM_0_0/CHAR_ROM_DISPLAY_RAM_RANGLER_FSM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_RAM_RANGLER_FSM_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_RAM_RANGLER_FSM_0_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_s00_regslice_0/CHAR_ROM_DISPLAY_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_s00_regslice_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_s00_regslice_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_s00_data_fifo_0/CHAR_ROM_DISPLAY_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_s00_data_fifo_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_s00_data_fifo_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_auto_pc_0/CHAR_ROM_DISPLAY_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_auto_pc_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_auto_pc_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_m00_data_fifo_0/CHAR_ROM_DISPLAY_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_m00_data_fifo_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_m00_data_fifo_0} -quiet] -quiet

# IP: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_m00_regslice_0/CHAR_ROM_DISPLAY_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_m00_regslice_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_m00_regslice_0} -quiet] -quiet

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_clk_wiz_0_0/CHAR_ROM_DISPLAY_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_clk_wiz_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_clk_wiz_0_0/CHAR_ROM_DISPLAY_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_clk_wiz_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_clk_wiz_0_0/CHAR_ROM_DISPLAY_clk_wiz_0_0_ooc.xdc

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_processing_system7_0_0/CHAR_ROM_DISPLAY_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_processing_system7_0_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_rst_ps7_0_50M_0/CHAR_ROM_DISPLAY_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_rst_ps7_0_50M_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_rst_ps7_0_50M_0/CHAR_ROM_DISPLAY_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_rst_ps7_0_50M_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_s00_regslice_0/CHAR_ROM_DISPLAY_s00_regslice_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_s00_regslice_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_s00_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_s00_regslice_0/CHAR_ROM_DISPLAY_s00_regslice_0_ooc.xdc

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_s00_data_fifo_0/CHAR_ROM_DISPLAY_s00_data_fifo_0_ooc.xdc

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_auto_pc_0/CHAR_ROM_DISPLAY_auto_pc_0_ooc.xdc

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_m00_data_fifo_0/CHAR_ROM_DISPLAY_m00_data_fifo_0_ooc.xdc

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_m00_regslice_0/CHAR_ROM_DISPLAY_m00_regslice_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CHAR_ROM_DISPLAY_m00_regslice_0 || ORIG_REF_NAME==CHAR_ROM_DISPLAY_m00_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/CHAR_ROM_DISPLAY/ip/CHAR_ROM_DISPLAY_m00_regslice_0/CHAR_ROM_DISPLAY_m00_regslice_0_ooc.xdc

# XDC: bd/CHAR_ROM_DISPLAY/CHAR_ROM_DISPLAY_ooc.xdc
