@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue Nov 13 15:34:52 -0800 2018
=======
<<<<<<< HEAD
REM Generated by Vivado on Sat Nov 10 21:42:45 -0800 2018
=======
REM Generated by Vivado on Fri Nov 09 16:12:11 -0800 2018
>>>>>>> 8c676840f2d6ed352e8a720fb7e570aabcf8c2b5
>>>>>>> f5b32d4ca83d31785747b52779843e931249981e
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim test_SERIAL_ADDER_behav -key {Behavioral:sim_1:Functional:test_SERIAL_ADDER} -tclbatch test_SERIAL_ADDER.tcl -view C:/Users/Necryotiks/AppData/Roaming/SPB_Data/WSU-CPTE/Module_11/test_SERIAL_ADDER_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
